export { default as Hero } from "./Hero"
export { default as About } from "./About"
export { default as Solutions } from "./Solutions"
export { default as FAQ } from "./FAQ"
export { default as Contact } from "./Contact"
